package com.pixelquest.app.domain.ai

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * Structured data model representing an AI habit coaching insight generated by Google Gemini.
 *
 * @param summary High-level observation of recent habit patterns and momentum.
 * @param suggestion Actionable recommendation for building or sustaining consistency.
 * @param encouragement Motivating closing sentiment celebrating progress.
 * @param highlightCategory Category that demonstrated standout performance or opportunity.
 * @param specificTaskCallout Optional category-level focus tip (non-PII).
 * @param generatedAt Timestamp when the insight was synthesized.
 */
@Serializable
data class HabitInsightResponse(
    val summary: String,
    val suggestion: String,
    val encouragement: String,
    val highlightCategory: String? = null,
    val specificTaskCallout: String? = null,
    val generatedAt: Long = System.currentTimeMillis()
) {
    companion object {
        private val json = Json {
            ignoreUnknownKeys = true
            isLenient = true
        }

        private val MARKDOWN_JSON_REGEX = Regex("```(?:json)?\\s*([\\s\\S]*?)\\s*```", RegexOption.IGNORE_CASE)

        /**
         * Parses a raw Gemini response string into a [HabitInsightResponse].
         * Safely strips markdown code blocks (e.g. ```json ... ```) or conversational preambles/postambles
         * and extracts structured fields.
         *
         * @throws IllegalArgumentException if the JSON is malformed or required fields are missing.
         */
        fun parseFromJson(rawResponse: String): HabitInsightResponse {
            val sanitized = sanitizeJsonString(rawResponse)
            val jsonObject = try {
                json.parseToJsonElement(sanitized).jsonObject
            } catch (e: Exception) {
                throw IllegalArgumentException("Malformed JSON payload: ${e.message}", e)
            }

            val summary = jsonObject["summary"]?.jsonPrimitive?.content?.trim()
            val suggestion = jsonObject["suggestion"]?.jsonPrimitive?.content?.trim()
            val encouragement = jsonObject["encouragement"]?.jsonPrimitive?.content?.trim()

            if (summary.isNullOrBlank() || suggestion.isNullOrBlank() || encouragement.isNullOrBlank()) {
                throw IllegalArgumentException("Missing required insight fields in JSON: $sanitized")
            }

            val highlightCategory = jsonObject["highlightCategory"]?.jsonPrimitive?.content?.trim()
                ?.takeIf { it.isNotBlank() && !it.equals("null", ignoreCase = true) }
            val specificTaskCallout = jsonObject["specificTaskCallout"]?.jsonPrimitive?.content?.trim()
                ?.takeIf { it.isNotBlank() && !it.equals("null", ignoreCase = true) }

            return HabitInsightResponse(
                summary = summary,
                suggestion = suggestion,
                encouragement = encouragement,
                highlightCategory = highlightCategory,
                specificTaskCallout = specificTaskCallout
            )
        }

        private fun sanitizeJsonString(raw: String): String {
            val trimmed = raw.trim()

            // 1. Look for markdown code fences (even with surrounding conversational text)
            val match = MARKDOWN_JSON_REGEX.find(trimmed)
            if (match != null) {
                val extracted = match.groupValues[1].trim()
                if (extracted.startsWith("{") && extracted.endsWith("}")) {
                    return extracted
                }
            }

            // 2. If no valid code fence, extract substring from first '{' to last '}'
            val firstBrace = trimmed.indexOf('{')
            val lastBrace = trimmed.lastIndexOf('}')
            if (firstBrace != -1 && lastBrace != -1 && lastBrace > firstBrace) {
                return trimmed.substring(firstBrace, lastBrace + 1).trim()
            }

            // 3. Fallback to direct trimmed string (which will throw clear exception in parser if invalid)
            return trimmed
        }
    }
}
