package com.pixelquest.app.domain.ai

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * Structured data model representing an AI habit coaching insight generated by Google Gemini.
 *
 * @param summary High-level observation of recent habit patterns and momentum.
 * @param suggestion Actionable recommendation for building or sustaining consistency.
 * @param encouragement Motivating closing sentiment celebrating progress.
 * @param highlightCategory Category that demonstrated standout performance or opportunity.
 * @param specificTaskCallout Optional category-level focus tip (non-PII).
 * @param generatedAt Timestamp when the insight was synthesized.
 */
@Serializable
data class HabitInsightResponse(
    val summary: String,
    val suggestion: String,
    val encouragement: String,
    val highlightCategory: String? = null,
    val specificTaskCallout: String? = null,
    val generatedAt: Long = System.currentTimeMillis()
) {
    companion object {
        private val json = Json {
            ignoreUnknownKeys = true
            isLenient = true
        }

        /**
         * Parses a raw Gemini response string into a [HabitInsightResponse].
         * Safely strips markdown code blocks (e.g. ```json ... ```) and extracts fields.
         *
         * @throws IllegalArgumentException if the JSON is malformed or required fields are missing.
         */
        fun parseFromJson(rawResponse: String): HabitInsightResponse {
            val sanitized = sanitizeJsonString(rawResponse)
            val jsonObject = try {
                json.parseToJsonElement(sanitized).jsonObject
            } catch (e: Exception) {
                throw IllegalArgumentException("Malformed JSON payload: ${e.message}", e)
            }

            val summary = jsonObject["summary"]?.jsonPrimitive?.content?.trim()
            val suggestion = jsonObject["suggestion"]?.jsonPrimitive?.content?.trim()
            val encouragement = jsonObject["encouragement"]?.jsonPrimitive?.content?.trim()

            if (summary.isNullOrBlank() || suggestion.isNullOrBlank() || encouragement.isNullOrBlank()) {
                throw IllegalArgumentException("Missing required insight fields in JSON: $sanitized")
            }

            val highlightCategory = jsonObject["highlightCategory"]?.jsonPrimitive?.content?.trim()?.ifBlank { null }
            val specificTaskCallout = jsonObject["specificTaskCallout"]?.jsonPrimitive?.content?.trim()?.ifBlank { null }

            return HabitInsightResponse(
                summary = summary,
                suggestion = suggestion,
                encouragement = encouragement,
                highlightCategory = highlightCategory,
                specificTaskCallout = specificTaskCallout
            )
        }

        private fun sanitizeJsonString(raw: String): String {
            var trimmed = raw.trim()
            // Strip markdown json block fences if the model wraps the output
            if (trimmed.startsWith("```json")) {
                trimmed = trimmed.removePrefix("```json").trim()
            } else if (trimmed.startsWith("```")) {
                trimmed = trimmed.removePrefix("```").trim()
            }
            if (trimmed.endsWith("```")) {
                trimmed = trimmed.removeSuffix("```").trim()
            }
            return trimmed
        }
    }
}
