package com.pixelquest.app.ui.screens.insight

import com.pixelquest.app.domain.ai.HabitInsightResponse

/**
 * Step 11 & 13: UI state hierarchy representing the AI habit insight screen.
 */
sealed interface AiInsightUiState {

    /**
     * Initial or active network generation in progress.
     */
    object Loading : AiInsightUiState

    /**
     * Successfully resolved AI habit insight (fresh or cached).
     *
     * @param insight Structured habit analysis.
     * @param isCached True if retrieved from local Room cache, false if freshly generated by Gemini.
     * @param remainingCooldownSeconds Seconds remaining until a live refresh is allowed (0 if ready).
     * @param canRefresh True if cooldown has passed and player may request a fresh insight.
     */
    data class Success(
        val insight: HabitInsightResponse,
        val isCached: Boolean = false,
        val remainingCooldownSeconds: Long = 0L,
        val canRefresh: Boolean = remainingCooldownSeconds == 0L
    ) : AiInsightUiState

    /**
     * AI Habit Insights are disabled in Settings (opt-in = false).
     */
    data class Disabled(
        val message: String = "AI Habit Insights are disabled. Enable them in Settings to receive personalized habit coaching."
    ) : AiInsightUiState

    /**
     * Live API call throttled by the 6-hour rate limit interval.
     */
    data class RateLimited(
        val retryAfterSeconds: Long,
        val message: String,
        val lastInsight: HabitInsightResponse? = null
    ) : AiInsightUiState

    /**
     * Step 13: Distinct encouraging state when player has fewer than 3 days of logged habits,
     * guiding them toward unlocking insights rather than presenting an error.
     */
    data class NotEnoughData(
        val daysLogged: Int = 0,
        val minimumRequiredDays: Int = 3,
        val message: String = "Keep adventuring! Complete daily quests for at least 3 days to unlock AI-powered Questmaster Insights.",
        val encouragingTip: String = "Every legend begins with a single step. Return after logging more momentum!"
    ) : AiInsightUiState {
        val remainingDaysNeeded: Int
            get() = (minimumRequiredDays - daysLogged).coerceAtLeast(1)
        val progressRatio: Float
            get() = (daysLogged.toFloat() / minimumRequiredDays).coerceIn(0f, 1f)
    }

    /**
     * Unrecoverable error (e.g. offline with empty cache, API outage).
     */
    data class Error(
        val message: String,
        val canRetry: Boolean = true,
        val fallbackInsight: HabitInsightResponse? = null
    ) : AiInsightUiState
}
